


-- devuelve todos los productos q fueron comprados por un cliente 

DELIMITER //
CREATE FUNCTION COMPRAS_USUARIO
(@USUARIO AS VARCHAR (30))
  RETURNS TABLE
AS
 RETURN(SELECT U.NOMBRE AS USUARIO , P.NOMBRE AS PRODUCTO FROM USUARIO U INNER JOIN PRODUCTOS P
       WHERE U.NOMBRE = @USUARIO);

DELIMITER ;

SELECT * FROM COMPRAS_USUARIO('Orla Lester')


-- calcula el total de compras

CREATE FUNCTION FN_TOTAL ()
RETURNS INT 
DETERMINISTIC 
BEGIN 
DECLARE  TOTAL_TABLA INT;
SELECT COUNT(TOTAL) INTO TOTAL_TABLA FROM COMPRAS;
RETURN TOTAL_TABLA;
END 
