--sql

-- crea vistas de los compras del ultimo año

 CREATE VIEW MOVIMIENTOS_ANIO_ACTUAL
 AS SELECT FECHA, TOTAL
 FROM COMPRAS
 WHERE FECHA > 01012022;

-- crea vista de provedores y su telefono

 CREATE VIEW PROVEDORES_TELEFONO
 AS SELECT NOMBRE , TELEFONO
 FROM PROVEDORES
 ORDER BY NOMBRE ;

 -- crea vista de productos y provedores

CREATE VIEW PRODUCTOS_PROVEDORES AS
SELECT e.NOMBRE AS NOMBRE_PRODUCTO, e.CLAVE AS CLAVE_PRODUCTO, r.NOMBRE AS NOMBRE_PROVEDOR, r.CORREO AS CORREO_PROVEDOR
FROM PRODUCTOS e
INNER JOIN PROVEDORES r
ON e.ID_PROVEDORES = r.ID_PROVEDORES;
 
 -- crea vista de productos y su categoria
 

CREATE VIEW PRODUCTOS_CATEGORIA AS
SELECT e.NOMBRE AS NOMBRE_CATEGORIA, e.CLAVE AS CLAVE_CATEGORIA, r.NOMBRE AS NOMBRE_PRODUCTO
FROM PRODUCTOS r
INNER JOIN CATEGORIAS e
ON e.ID_CATEGORIAS = r.ID_CATEGORIAS;


-- crea vista de compras y usuarios 

CREATE VIEW VENTA_PRODUCTOS AS
SELECT C.*, P.NOMBRE AS PRODUCTO, P.PRECIO, U.NOMBRE AS USUARIO, U.DIRECCION, U.TELEFONO
FROM COMPRAS C
INNER JOIN PRODUCTOS P ON P.ID_PRODUCTOS = C.ID_PRODUCTOS
INNER JOIN USUARIOS U ON U.ID_USUARIOS = C.ID_USUARIOS
