--sql

-- crea vistas de los compras del ultimo año

 CREATE VIEW MOVIMIENTOS_ANIO_ACTUAL
 AS SELECT FECHA, TOTAL
 FROM COMPRAS
 WHERE FECHA > 01012022;

-- crea vista de provedores y su telefono

 CREATE VIEW PROVEDORES_TELEFONO
 AS SELECT NAME, TELEFONO
 FROM PROVEDORES
 ORDER BY NAME;

 -- crea vista de productos y provedores

 CREATE VIEW PRODUCTOS_PROVEDORES
 AS SELECT (e.NOMBRE,e.CLAVE,r.NOMBRE,r.CORREO)
 FROM PRODUCTOS e, PROVEDORES r
 WHERE e.ID_PROVEDORES = r.ID_PROVEDORES;
 
 -- crea vista de productos y su categoria
 
 CREATE VIEW PRODUCTOS_CATEGORIA
 AS SELECT (e.NOMBRE,e.CLAVE,r.NOMBRE,r.CORREO)
 FROM PRODUCTOS e, CATEGORIA r
 WHERE e.ID_CATEGORIAS = r.ID_CATEGORIAS;

-- crea vista de compras y usuarios 

 CREATE VIEW COMPRA_USUARIO
 AS SELECT (e.FECHA,e.TOTAL,r.CORREO,t.CLAVE)
 FROM COMPRAS e, USUARIOS r, PRODUCTOS t
 WHERE e.ID_PRODUCTOS = t.ID_PRODUCTOS
 AND   e.ID_USUARIOS = r.ID_USUARIOS ;
